sudo: false
language: python

matrix:
  include:
    - env: TOXENV=django111-py36
      python: 3.6
    - env: TOXENV=django111-py37
      python: 3.7
    - env: TOXENV=django111-py38
      python: 3.8
    - env: TOXENV=django111-py39
      python: 3.9
    - env: TOXENV=django22-py36
      python: 3.6
    - env: TOXENV=django22-py37
      python: 3.7
    - env: TOXENV=django22-py38
      python: 3.8
    - env: TOXENV=django22-py39
      python: 3.9
    - env: TOXENV=django30-py36
      python: 3.6
    - env: TOXENV=django30-py37
      python: 3.7
    - env: TOXENV=django30-py38
      python: 3.8
    - env: TOXENV=django30-py39
      python: 3.9
    - env: TOXENV=django32-py36
      python: 3.6
    - env: TOXENV=django32-py37
      python: 3.7
    - env: TOXENV=django32-py38
      python: 3.8
    - env: TOXENV=django32-py39
      python: 3.9

install:
  - pip install coveralls tox

script:
  - tox

after_success:
  - coveralls
